"""change in project table

Revision ID: a6c5afd29922
Revises: 68156aadf4ce
Create Date: 2026-01-06 18:49:37.737688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c5afd29922'
down_revision: Union[str, Sequence[str], None] = '68156aadf4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('avgRating', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('ratingCount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'ratingCount')
    op.drop_column('projects', 'avgRating')
    # ### end Alembic commands ###
